spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5454/java15
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
    messages:
        basename: messages

server:

    port: 9797
    error:
        include-message: always


app:
    security:
        jwt:
            secret_key: java15-jwt-token-skdjfksljdflksjearsdkfjksdjfskldjfsl
            expiration: 604800
